import * as fs from 'fs/promises';
import * as path from 'path';

export const CLAUDE_MD_AUTOGEN_START = '<!-- CIT:CLAUDE_MD_AUTOGEN_START -->';
export const CLAUDE_MD_AUTOGEN_END = '<!-- CIT:CLAUDE_MD_AUTOGEN_END -->';

export function upsertAutoGeneratedClaudeMdBlock(existing: string, generated: string): { content: string; replaced: boolean } {
  const managedBlock = `${CLAUDE_MD_AUTOGEN_START}\n\n${generated.trim()}\n\n${CLAUDE_MD_AUTOGEN_END}`;
  const blockPattern = new RegExp(
    `${CLAUDE_MD_AUTOGEN_START}[\\s\\S]*?${CLAUDE_MD_AUTOGEN_END}`,
    'm'
  );

  if (blockPattern.test(existing)) {
    return {
      content: existing.replace(blockPattern, managedBlock),
      replaced: true,
    };
  }

  const separator = existing.trim().length > 0 ? '\n\n' : '';
  return {
    content: `${existing}${separator}${managedBlock}\n`,
    replaced: false,
  };
}

export async function applyClaudeMdSuggestionsSafely(targetPath: string, generated: string): Promise<{
  created: boolean;
  replaced: boolean;
  backupPath?: string;
}> {
  let existing = '';
  let created = false;

  try {
    existing = await fs.readFile(targetPath, 'utf-8');
  } catch {
    created = true;
  }

  const { content, replaced } = upsertAutoGeneratedClaudeMdBlock(existing, generated);
  let backupPath: string | undefined;

  if (!created) {
    backupPath = `${targetPath}.bak.${Date.now()}`;
    await fs.writeFile(backupPath, existing, 'utf-8');
  }

  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, content, 'utf-8');

  return { created, replaced, backupPath };
}
